<?php

/**
 * public function test_VerifyLog_Reason_TheFirstPosition_NotInit_ThrowsException
 * public function test_VerifyLog_Reason_TheLastPosition_NotSleep_ThrowsException
 * public function test_VerifyLog_Reason_Init_NotAtTheFirstPosition_ThrowsException
 * public function test_VerifyLog_Reason_Action_AtTheFirstPosition_ThrowsException
 * public function test_VerifyLog_Reason_Action_AtTheLastPosition_ThrowsException
 * public function test_VerifyLog_Reason_Reset_AtTheFirstPosition_ThrowsException
 * public function test_VerifyLog_Reason_Reset_AtTheLastPosition_ThrowsException
 * public function test_VerifyLog_Reason_Wakeup_NotAfterSleep_ThrowsException
 * public function test_VerifyLog_Reason_Sleep_NotAtTheLastPosition_NotBeforeWakeup_ThrowsException
 */
class Fsm_VerifyLog_ReasonTest extends Fsm_VerifyLogTestCase
{
}
